### ISSUE TITLE
Suggestions for CSS improvements

### ISSUE THREAD

**Issue by GeckoEidechse** [R2NorthstarTools/FlightCore#104]
Suggestions made by @barnabwhy in private channels based on TFOR launcher source code

```css
:root {
    --background-image: url("../bg/img/arc.png") center / cover;
    --background-image-fallback: url("../bg/img/arc.png") center / cover;
    --background-color: rgb(23, 51, 107);
    --background-color-transparent: rgb(23, 51, 107, 0.85);
    --background-gradient: linear-gradient(transparent 25%, var(--background-color-transparent) 75%, var(--background-color) 90%), var(--background-image), var(--background-image-fallback);
    --background-color-secondary: rgb(14, 25, 47);
}

body {
    background: var(--background-gradient);
}
```
https://discord.com/channels/920776187884732556/1043871335543214102/1048643323755233401
